- themes.json
- themes/Riot.tmTheme
> added Riot.tmTheme and updated themes.json

- README.md
- themes.json
quick update for my new handle
> updating readme

- themes.json
- themes/Hammer.tmTheme
I ran the test and it passed. My theme has been around for a while and has 1k users.
https://github.com/jared-christensen/sublime-2-color-scheme-hammer
> Added Hammer

- themes.json
- themes/NeonGlow.tmTheme
> Added my neon theme as Neon Glow

- package.json
- tests/themes-exist.spec.js
- tests/themes-parsing.spec.js
- themes/Acai.tmTheme
- themes/Brilliance_Black.tmTheme
- themes/Brilliance_Dull.tmTheme
- themes/Dark-Dracula.tmTheme
- themes/Focus_Dark.tmTheme
- themes/Focus_Light.tmTheme
- themes/GoldenDragon.tmTheme
- themes/ant.tmTheme
> Add libxmljs and test to check for valid XML

- themes.json
- themes/Humane.tmTheme
> add `Humane.tmTheme`

- themes.json
- themes/Zeus-Sublime-Text.tmTheme
> Add Zeus Color Scheme

- README.md
- themes.json
- themes/Wildlife-Day.tmTheme
- themes/Wildlife-Night.tmTheme
Added Wildlife (Day and Night theme)
Updated themes.json and README.md
> added Wildlife theme

- themes.json
- themes/Frozen.tmTheme
> Frozen theme added

- themes.json
- themes/New-Day.tmTheme
Hi! Here's a new theme based on Nette. Suitable for daylight, tested with the following syntax definitions:
- html5
- scss
- javascript (using ultimate javascript package)
- php
- jade
- smarty
Regards
> New Day theme

- themes/New-Day.tmTheme
I updated the theme, added some more colors to scss and javascript.
> 'New Day' theme update

- themes/New-Day.tmTheme
new update: better embedded php, as for the title
> new day: better embedded php

- themes.json
- themes/Late_Night.tmTheme
Hopefully you will add mine too :)
The theme is called 'Late Night' - it is a dark theme optimised for better readability (less difference in saturation and brightness between tokens)
> Late Night theme by YemSalat

- themes/AgolaDark.tmTheme
https://github.com/UnderlineWords/Agola-Color-Schemes/issues/2
> Updated version for Agola Dark

- README.md
- themes.json
- themes/Github-v2.tmTheme
Added new Github color scheme. This has almost the exactly same color scheme used in github.com, except background color. Only tested with ruby, coffeescript, and sass.
> Add github-v2 color scheme

- themes.json
- themes/Solarized-dark (Nitrous).tmTheme
- themes/Solarized-dark-Nitrous.io.tmTheme
This is Solarized dark version used in [Nitrous.io](http://nitrous.io).
> Add new theme - Solarized dark Nitrous.io version

- README.md
- themes.json
- themes/MarsPeacock.tmTheme
See [original repository](https://github.com/Odepax/mars-peacock) for previews.
> Add Mars Peacock scheme

- themes/Henanigans.tmTheme
My color palette of a slightly older version and so was off
I tweaked it and this should be my last commit
> tweaked colors

- themes.json
- themes/DarkKorokai.tmTheme
Added DarkKorokai Theme by WhosMyName
> Added DarkKorokai Theme by WhosMyName

- themes/Another_Kolor_Dark.tmTheme
Modify Foreground Color and JavaScript Colors in the Dark Theme
Changed the foreground color of text in the Dark theme from a light grey
to white in order to make content stand out better in HTML markup.
Changed the JavaScript function call colors to add more color
variability. When testing with a local Gulp configuration file, there
was too much gold in the color scheme.
* Changed global foreground color from #969696 to #FFFFFF (line 31)
* Changed global selection color from #3F352A to #3C3C3C (line 43)
* Changed global selection border color from #3F352A to #3C3C3C (line
* 45)
* Redirect to the stored location after successfully logging in the user
* Changed comment color from #525252 to #3D3D3D (line 58)
* Changed variable color from #FCD660 to #abe9fb (line 157)
* Changed function …
> Another Kolor Theme Update

- themes/Another_Kolor_Dark.tmTheme
- themes/Another_Kolor_Light.tmTheme
Includes latest revisions as of 16 July 2016.
See GitHub Repo for Details:
https://github.com/danyadsmith/AnotherKolor
> Updated theme AnotherKolor (Dark and Light variants) by Danya D. Smith

- .travis.yml
- package.json
Updating libxmljs fixes `npm install` on OSX. Also updated Chai for funsies.
> Fix #194: Update libxmljs and chai

- themes.json
- themes/blockninja.tmTheme
Add our ST3 theme, "blockninja" - a dark theme with blues & purples
> Add "blockninja" theme

- README.md
- themes.json
- themes/karyfoundation-dark.tmTheme
- themes/karyfoundation-light.tmTheme
`Kary Foundation - Light` and `Kary Foundation - Dark` added.
> Kary Foundation themes added.

- themes.json
- themes/Adventure_Time.tmTheme
Added a port of the adventurous syntax from Atom with slight changes for ES6 support.
Original Github: https://github.com/philpl/Adventurous-Syntax
> Adventure Time Color Theme Addition

- README.md
- themes/Neon_Kush.tmTheme
Small fix on my previous Theme, Neon Kush. Fixed Readme to Include my name and account as well.
> Small fix on my previous Theme, Neon Kush. Fixed Readme

- themes/Another_Kolor_Dark.tmTheme
- themes/Another_Kolor_Light.tmTheme
Adds minor theme updates for JavaScript and other syntaxes. Details at this repo: https://github.com/danyadsmith/AnotherKolor
>  Updated theme AnotherKolor (Dark and Light variants) by Danya D. Smith

- themes/Oceanic-Reef.tmTheme
Hi, i made a minor update for the self keyword for Python and Ruby languages. to improve it's visual look.
> Minor update for Python and Ruby

- themes.json
- themes/Legatus.tmTheme
> Add Legatus.tmTheme

- README.md
alphabetizes the author list and pulls missing authors from themes.json file.
> Authorlist

- themes.json
- themes/Martian.tmTheme
> Added Martian theme (v1.0)

- README.md
- themes.json
- themes/Visual_Studio_Dark_Plus.tmTheme
source: https://github.com/vidann1/visual-studio-dark-plus
> Add Visual Studio Code Dark+ Theme

- themes/Birds_of_Paradise.tmTheme
Please review if colors are correctly applied to the new definitions
> A small update to have better behavior in Python
